### PR TITLE
Automatically detect language of posts, improve language detection when posting

### PR DESCRIPTION
**Pull request by Havhingstor**
The target-language for the translation option is automatically determined via Apple's NaturalLanguage-Library. The detection works similar to the already implemented detection when posting, but hashtags, emojis (*:emoji:*) and "@"-links are filtered out, so that the processed text is cleaner. If the detected language is wrong the user still has the option to translate from the transmitted (*"secondary"*) language in the context menu.
The language-detection when posting is also reworked: The language is always detected, even when the user explicitly selected another one. The user is however always asked in which language he wants to post, since quietly changing the language before posting can confuse.

That should address issue #747 at least to a certain degree.

Optionally I could also see a scenario where the translation from the secondary language is also accessible via a button in main view (not only the context-menu). That might be easier to understand, depending on the accuracy of the language detection.

### CODE REVIEW

**Comment by Havhingstor** [comment]
It might also be possible to find a better replacement for "secondary" language, maybe "transmitted" or "set" language

**Comment by nekolaboratory** [comment]
May be "Secondary language" might be rephrased as "other candidates".

**Comment by Dimillian** [comment]
This is really good for the editor part, for the status part I'm not sure we want to take in the performances hit it brings.
Processing the string and detecting the language as you scroll the timeline is heavy. 
It would need to be async for it to be safer, but if we do that, then it means it'll update the button once it's done processing, and this would also brings lag with SwiftUI. The lazy var you have don't really protect anything as it's called while dequeing / scrolling statuses.

I recommend removing the part in the status row and keeping the part with the langage detection in the editor, because this is really great.

**Comment by Dimillian** [comment]
I've changed a bit the code on main: 

- It now prefer to use the Mastodon API when available
- I'm not forcing the lang of the post to be different from the user lang (local or server) anymore to show the translate option in the ... menu. 

I think your change are great, but you can drop the one in the status, let just have the confirmation from the editor before posting.

**Comment by Havhingstor** [comment]
I've removed the language-detection on the timeline for now. I might come back to it later on, but for now I've focused on the editor.

**Pull request merged**
