### PR TITLE
Removed toggle for selecting themes and replaced with picker.

### PR DESCRIPTION
**Pull request by PrajeetShrestha**
- Removed toggle for selecting themes and replaced with picker.  This will help us add more themes later on. 
- Themes added
     1. IceCube - Dark / Light
     2. Desert - Dark / Light
     3. Nemesis - Dark / Light

### CODE REVIEW

**Review by Dimillian — APPROVED** [review]
I love it! This is awesome! Love the new themes. Let me know when I can merge :)

**Comment by Dimillian** [comment]
Actually, since I approved I think you can merge whenever you want

**Comment by PrajeetShrestha** [comment]
> I love it! This is awesome! Love the new themes. Let me know when I can merge :)

Thank you :). You can merge it. Since I don't have write access, I can't merge.

**Comment by Dimillian** [comment]
I'll, and I'll look how to enable merge when the PR is reviewed.

**Pull request merged**
