### PR TITLE
Highlight timeline row where I am mentioned

### PR DESCRIPTION
**Pull request by EvilOne**
Short PR to highlight a timeline row where the current user is mentioned.
CleanShot 2023-01-30 at 18 24 58@2x

### CODE REVIEW

**Comment by Dimillian** [comment]
I'm careful with this one, will need to do some checks when I'll have time but I think it could create some performances issues, as the var is computed at scroll time.

**Comment by seanlifetime** [comment]
Sounds like a plan. Performance is important. 

Thanks!

**Comment by Dimillian** [comment]
Closing it for now, I still want it in, but I'll think of a different way to do it. I'm super careful now when adding computed stuff to the timeline.

**Comment by EvilOne** [comment]
I am working on something that doesn't do it at the var level for the timeline.

**Pull request closed without merging**
