### PR TITLE
Fonts

### PR DESCRIPTION
**Pull request by xurble**
Addresses #599 

This installs 2 custom fonts: OpenDyslexic and also Atkinson Hyperlegible for accessibility reasons.

But to satisfy the licensing requirements, it also adds a basic About screen to settings with a link to those fonts and, for completeness, all the open source libraries Ice Cubes uses.

### CODE REVIEW

**Comment by Dimillian** [comment]
Unexpected About screen but super nice!

**Comment by Dimillian** [comment]
So, on device, the font picker controller don't display those two fonts :/ @xurble can't really understand why.

**Comment by xurble** [comment]
Sorry about that.  Obviously it worked in testing.  If I had to guess, I think it will be this setting.

Screenshot 2023-02-04 at 08 09 28

**Comment by xurble** [comment]
I would check "Install Fonts"

**Comment by Dimillian** [comment]
Let's try.

**Pull request merged**
