### PR TITLE
Added a tip that it's a video, and not an image when autoplay is off

### PR DESCRIPTION
**Pull request by Dean151**
**Motivation**:
When autoplay is off in the settings, images are not distinguishable from videos. To prevent missing fun or info from videos, we need tip them

**Proposed solution**:
Adding a "play" tip at the bottom left ; with the same stylish than "ALT"
The play tip only shows when autoplay is off.
The position have been chosen to not overlay with VideoPlayer standard controls that might appear sometime.

Screenshot of the actual look of the video tip

### CODE REVIEW

**Comment by sothawo** [comment]
My personal preferences would be:
* center the overlay in the middle of the image, it might be missed in the corner
* make it a little larger

**Comment by Dean151** [comment]
That was my first attempt, but as the viewer in the timeline is a full AVPlayer, sometime the controls would appear and overlay and we have little control over that with VideoPlayer from SwiftUI. Unless switching VideoPlayer with a Image, with a lot of work, or using a ViewRepresentable mecanism to embed a AVPlayerController, this is ugly.

**Comment by Dean151** [comment]
I've made an update ; proposing a solution.

It's still overlaying with Player controls at some occasions, but since the "tip" is large enough, the play button is completely hidden behind the circle.

So this is what it looks like now:

new preview for video tip new preview with player control overlays src=

**Comment by Dimillian** [comment]
Feel fine to me now. Until we have a better video player integration, it's ok to have that. I wish I could auto play video in QuickLook but it's not the case :/

**Comment by sothawo** [comment]
I dont see the tip overlaying the video when playing (running on your checked out branch), when starting the video, it opens in a new window

**Comment by Dean151** [comment]
> Feel fine to me now. Until we have a better video player integration, it's ok to have that. I wish I could auto play video in QuickLook but it's not the case :/

@dimillian I think it would be time to consider leaving Quicklook ; and starting to have something more custom with more control over media previews ; and full screen view.

**Pull request merged**
