### PR TITLE
Implement language selection for new posts

### LINKED ISSUE #76: [Feature request] Option to select post's language in the composer
It is important for multi-language people to indicate the language of their post.

The `/api/v1/statuses` endpoint accepts a `language` parameter. Its value should be a ISO 639 language code that represents the language of a status update. On the official Mastodon UI, this can be selected using the language icon.

IMG_0174

Ice Cubes could have a similar button in the New Post composer. It could be placed between the CW and Drafts buttons on the toolbar. The default language could be derived from the system language.

### PR DESCRIPTION
**Pull request by vollkorntomate**
This PR adds the ability to select a new post's language. It takes into account the preference set by the user (sent by the server). Replies take the language of the parent post by default.

Preview (the simulator is set to English as first and German as second language):
image

Closes #76

### CODE REVIEW

**Comment by EvilOne** [comment]
I cannot get the globe icon to show when I post a message. Would this happen in only certain cases? I see the following:



And here is what the xCode console shows:
CleanShot 2023-01-16 at 18 05 54@2x

**Comment by EvilOne** [comment]
But when I reply, I do get the language set and can set a different language.

**Comment by Dimillian** [comment]
@EvilOne Fixing it, it's probably because your account don't have a default language, I'm setting the default to English. 
@vollkorntomate Good works! I'll do a few fixed and merge it! 

I think an improvement could be to show a sheet instead and add search into it. Would make it easier to browse languages.

**Comment by Dimillian** [comment]
image

**Comment by EvilOne** [comment]
@Dimillian  Good to know. Even with the latest TestFlight build I still don't see the language selection option for new posts. Is this expected behaviour?

**Comment by Dimillian** [comment]
@EvilOne Are you sure? You should see the globe if no language is set hmmmm

**Comment by EvilOne** [comment]
@Dimillian here is what I see. 

image

image

**Comment by EvilOne** [comment]
Double checked to make sure I have the latest. image

**Comment by EvilOne** [comment]
One last thing. I checked my settings for posts and it is set to automatically determine language of post.

**Comment by Dimillian** [comment]
That's sooooo weird. My secondary account is like yours and it's showing the globe. Will investigate at some point if you don't find a fix first.

**Pull request merged**
