### PR TITLE
Fix leak memory (Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT))

### PR DESCRIPTION
**Pull request by nekolaboratory**
Closes: #829

### CODE REVIEW

**Comment by Dimillian** [comment]
Are you sure it did anything?

**Comment by nekolaboratory** [comment]
Yes.
The problem is exactly the same as #829, and it happens until you manually reload.

I found the reason for this problem when I debugged.

https://github.com/Dimillian/IceCubesApp/blob/5caa0b647879a3a34a3860f51eb413ab98162aab/Packages/Notifications/Sources/Notifications/NotificationRowView.swift#L110

https://github.com/Dimillian/IceCubesApp/blob/5caa0b647879a3a34a3860f51eb413ab98162aab/Packages/Notifications/Sources/Notifications/NotificationRowView.swift#L134

When you access notification.status in the above location, "(Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT))" occurs when you open the notification screen for the first time, causing an infinite loop.

This seemingly meaningless syntax solved that problem.

**Comment by Dimillian** [comment]
Are you sure an Xcode clean will not solve the issue? I've not been able to reproduce this crash and I see no report of it in the reporting.

**Comment by nekolaboratory** [comment]
We have confirmed that there is a bug in the official release version of IceCubesApp v1.5.1 installed from the App Store.

A cleanup of Xcode also reproduces the issue on the latest main branch.

By the way, the instance I checked is "best-friends.chat".

**Comment by Dimillian** [comment]
Well, it's crazy but ok.

**Pull request merged**
