### PR TITLE
Newer, better, faster HTML to Markdown converter

### PR DESCRIPTION
**Pull request by xurble**
It removes all the hacks and just uses the SwiftSoup parser

It will fix issue #576 and also an unlogged issue with the old implementation that could corrupt urls with underscores in them.

### CODE REVIEW

**Comment by xurble** [comment]
As a side effect, you can remove the HTML2Markdown dependency, which I haven't done in case its needed elsewhere.

**Comment by Dimillian** [comment]
This look epic but I'm afraid we would need to test it on a lot of statuses?

**Comment by xurble** [comment]
God yes!
It's on my phone at the moment.  It seems to fix all the known problem cases I have bookmarked.

**Comment by EvilOne** [comment]
@Dimillian @xurble to really test this change out, assuming what I propose is simple, how about an experimentation area in settings? Within there we would have render with new algorithm (not really suggestion this exact text) which would act asa feature flag. This feature flag, when active, would run this code instead of the existing code. The default would be off. 

Then when/if released like this can call it out in the release notes and such. 

Thoughts?

**Comment by Dimillian** [comment]
@EvilOne I'm waiting to fix the crash on timeline refresh so I can start the 1.4.0 train, my plain is to merge this as soon as 1.4.0 hit and use it for a few days to see if there is any regression. From what I've tested so far, I couldn't not find. 
I agree that a feature flag would be ideal but it complicates a bit the process

**Pull request merged**
