### PR TITLE
match intended mastodon presentation

### LINKED ISSUE #556: Feature request: Match the mastodon sever presentation of URLs
Currently URLs are displayed in full, but the server actually sends back a preferred presentation by wrapping parts of the displayed part in &lt;span class="invisible"> and &lt;span class="ellipsis">

The current way it's done can be quite noisy particularly for sites that put a lot of referrer tracking cruft on their urls e.g.

https://mstdn.social/@newscientist/108495364633319115

### PR DESCRIPTION
**Pull request by xurble**
Fixes #556 

strip out <span="invisible">blah</span>
append ellipsis to <span="ellipsis">blah</span>

### CODE REVIEW

**Comment by Dimillian** [comment]
What does it change visually?

**Comment by xurble** [comment]
This is an example.  It matches the mastodon web interface.

Simulator Screen Shot - iPhone 14 Pro - 2023-01-31 at 07 30 12

**Comment by xurble** [comment]
Or inline

Simulator Screen Shot - iPhone 14 Pro - 2023-01-31 at 07 31 43

**Comment by Dimillian** [comment]
Oh this is so nice! I didn't knew how to do it. And the link is still clickable to the right place?

**Comment by xurble** [comment]
Yep, it's just the display part.  Mastodon does the hard work for you.  The links are marked up with spans that can be discarded (or css styled away if you were on the web).

**Pull request merged**
