### PR TITLE
Tab Bar Icon Customisation

### LINKED ISSUE #1158: Feature request: Tab Bar Customisation
I'm working on the ability to choose between different sets of tab bar icons as well as other forms of tab bar customisations such as adjustable icon sizes.

### PR DESCRIPTION
**Pull request by vevek**
Closes #1158 

Added a tab bar icon set customisation option (Only for iPhones, not Mac or iPad yet). 

Hey @Dimillian the PR is ready to be merged, let me know if you'd like me to make any changes :)

**In future updates:**
- Will add the option to allow for each tab bar icon to be individually customisable (not as a set)
- Will add other forms of tab bar customisation options

**To everyone:**
It's easy to add more icon set options! Edits only need to be made to 
1) Packages/DesignSystem/Sources/DesignSystem/TabBarIconSet.swift and 
2) Packages/DesignSystem/Sources/DesignSystem/Theme.swift

**Screenshots:**
1:

2:

3:

4:

### CODE REVIEW

**Comment by sothawo** [comment]
To be honest, I don't see the benefit of just assigning some random images that have no relation whatsoever to the context to the buttons.

**Comment by vevek** [comment]
> To be honest, I don't see the benefit of just assigning some random images that have no relation whatsoever to the context to the buttons.

While the existing tab bar icon options are great, I found myself wanting to change the Timeline icon to the one in screenshot 1, option 2. For that icon  option, the image does have a relation to the button's context. 

I added the other options as it gives users the benefit of choice :) If @dimillian and you would like, I can remove some of the other options. Ultimately, even with some options removed, it is fairly straightforward to add others.

In the future I plan to make each tab bar icon completely customizable, such that provided icon set options are not needed, and users would be able select from a wide range of SF symbols. A custom tab bar (taking inspiration from Ivory) would be something I could work towards too!

**Comment by Dimillian** [comment]
Hello, thanks for the work on this PR. While I like the code, it unfortunately add some complexity to the codebase without providing a meaningful user facing improvements. I'm considering tabar tab customisation (modifying the order, allowing to set more tabs type, etc..) a good improvements. But changing icons probably not so much at this stage.

**Comment by Dimillian** [comment]
Closing this for now

**Pull request closed without merging**
