### PR TITLE
Add localisation plurals

### LINKED ISSUE #198: Minor bug: "1 new posts" incorrectly pluralised
Hi! Love the app.

The new-post notification says "1 new posts" instead of "1 new post".

It seems to be here in the code: https://github.com/Dimillian/IceCubesApp/blob/997a33df697e940a5310b01e1304eace1a7be60f/Packages/Timeline/Sources/Timeline/TimelineViewModel.swift#L52

I found this about pluralisation in Xcode: https://developer.apple.com/documentation/xcode/localizing-strings-that-contain-plurals

There seem to be a few more always-pluralised strings in https://github.com/Dimillian/IceCubesApp/blob/997a33df697e940a5310b01e1304eace1a7be60f/IceCubesApp/Resources/Localization/en.lproj/Localizable.strings.

### PR DESCRIPTION
**Pull request by EvilOne**
- Fixes #198, which adds a way to create plurals of words within the app.
- Also addresses #225

### CODE REVIEW

**Comment by Dimillian** [comment]
Looking at the two other PR we'll have to handle Italian and Chinese in there too. I'll look at it tomorrow once everything else will be merged. Buts it's great!

**Comment by EvilOne** [comment]
If you merge the other languages, I can quickly put them into this PR too

**Comment by EvilOne** [comment]
No rush from you, I know it is late.

**Comment by Dimillian** [comment]
All good, all other translations update are merged :)

**Comment by EvilOne** [comment]
@Dimillian updated. It looks like #262 doesn't update the key I had removed ("timeline.n-new-posts %lld"), which is good and shouldn't cause conflict issues. With that said, I recommend merging this before #262 since it has more updated translations.

**Comment by Dimillian** [comment]
Well let's go with this one!

**Comment by EvilOne** [comment]
Sounds good to me! We have to start somewhere!

**Pull request merged**
