### PR TITLE
Remove tab string from iOS app

### PR DESCRIPTION
**Pull request by nekolaboratory**
Fixed an issue where the display of tab menu names may be corrupted on iOS devices with small screens.

Closes:#654

### CODE REVIEW

**Comment by sothawo** [comment]
Instead of always removing the labels, I'd think to have this configurable (show labels with icons) would be a better way. Especially for new users who open the app for the first time, it might not be clear what these icons are without the explanation by the labels.

**Comment by Dimillian** [comment]
Definitely need to be a setting. And I've yet to pull it to see how it look but I hope iOS adapt the image bottom margin then.

**Comment by nekolaboratory** [comment]
I was of that opinion for a while.
However, depending on the language and label size, the characters may be cut off and it does not make sense.

I also refer to the fact that the Mastodon official app does not have an icon label by default.

Tab

**Comment by sothawo** [comment]
This is a very good example that making this configurable is the best way. For a user where the label is long and who has a small display it can be disabled. But I'd keep the label as default for everybody else.

**Comment by nekolaboratory** [comment]
Here is a screenshot of the simulator.

Simulator

Explicitly showing functions to users with strings is important, but considering the accessibility of people who use languages ​​that cannot read the default English and have not been translated, UI that can be conveyed only by icons is important.

**Comment by echidistanti** [comment]
Having it as an option is the optimal solution. Usability guidelines recommend labels, but we're talking about icons that, in this case, have universally recognized functionality, true pictographs

**Comment by Dimillian** [comment]
I like the idea, again. But this create a huge UI problem. The icons should be center aligned, and we can't do that in SwiftUI until we make a custom tabbar. 
I would be ok to merge it if it's an option in display settings, with a default to true (showing the label). Until then I can't merge it.

**Comment by nekolaboratory** [comment]
I understand your opinion.

Then we plan to find time and make changes to add a show/hide option to the settings screen.

**Comment by nekolaboratory** [comment]
@Dimillian
Discussed tab label display settings

What do normal users call the string under the tab icon?

Currently, it is set to Tab Name.

**Comment by Dimillian** [comment]
All good thanks!

**Pull request merged**
