### PR TITLE
Timeline: restore the selected timeline at the next startup

### PR DESCRIPTION
**Pull request by nekolaboratory**
Closes: #581

### CODE REVIEW

**Comment by Dimillian** [comment]
I think you need to rebase on main one more time, missing the `remoteLocal` new filter parameter.
It create when switching account for example, if you saved a list not available on the other account etc... 
And it'll also fail whenever I'll add new filters (but I guess this is fine). 
Also have to test the various login / logout configuration. 

I just think it's a lot of effort for such a small feature, and it could create unforeseen feature. Multi accounts being a problem right now with this feature.

**Comment by nekolaboratory** [comment]
I will fix that. Thank you!

**Comment by nekolaboratory** [comment]
Please review again.

**Comment by nekolaboratory** [comment]
https://github.com/Dimillian/IceCubesApp/pull/694

**Comment by nekolaboratory** [comment]
Please review again.

**Comment by nekolaboratory** [comment]
@Dimillian Regarding the account switch problem that you are concerned about, it is a little overbearing, but how about saving the state by limiting it to the tabs common to the account as follows?

```
    .onChange(of: timeline) { timeline in
      if(timeline == .home || timeline == .federated || timeline == .local) {
        lastTimelineFilter = timeline
      }
    }
```

**Comment by Dimillian** [comment]
@nekolaboratory Sound good. Unless it really break the feature as you would use it.

**Comment by nekolaboratory** [comment]
Thank you. Changes have already been committed.

**Comment by Dimillian** [comment]
Thanks! Let's give it a try!

**Comment by nekolaboratory** [comment]
Cheers!
On the Mastodon instance I'm based on, the local timeline is mainstream.
So being able to record the default timeline is a very useful feature.

Can't wait for the release!

**Pull request merged**
