### PR TITLE
Add Account: Sanitize the servername to remove http[s]:// and also usernames

### PR DESCRIPTION
**Pull request by xurble**
Fixes: #1120

### CODE REVIEW

**Comment by Dimillian** [comment]
Hmmm it break down when you tap on a suggestion and replace the domain.

**Comment by xurble** [comment]
Sorry, I thought instance.title was always the domain, but it's just mostly the domain.  Try now.

**Comment by Dimillian** [comment]
Thanks!

**Comment by thattridentdude** [comment]
Nice work!

**Pull request merged**
