### PR TITLE
Updated German localization

### PR DESCRIPTION
**Pull request by dertuxmalwieder**
- translated a few more strings
- unified "participants"

### CODE REVIEW

**Comment by jue89** [comment]
... and he silently un-gendered "Teilnehmende" ... /cc #398

**Comment by Dimillian** [comment]
That the kind of stuff I can't check. I guess we should define owner for localization soon so I'll not merged before an LGTM from the owner.

**Comment by dertuxmalwieder** [comment]
It would have to be “Teilnehmer:innen” to be consistent, so it was wrong either way…

**Comment by jue89** [comment]
I recapped my PoV in the related issue. I just wanted to create transparency which hasn't been done by @dertuxmalwieder ("unified" instead of "changed to generic masculine").

I won't continue these edit wars - it's eating up valuable time. And personally I'm not affected. But I have friends who would ... that's why I think gender-neutral language is worth to be considered.

**Pull request merged**
