### PR TITLE
Add Brazilian Portuguese Localization

### PR DESCRIPTION
**Pull request by arthurgivigir**
Hey from a new Mastodon Fan!
This is my first contribution on this amazing app, adding Brazilian Portuguese 🇧🇷.
Any problem, please reach me out!

### CODE REVIEW

**Comment by Dimillian** [comment]
Could you rebase one more time, we have a few new strings

**Comment by Dimillian** [comment]
Could you rebase one more time, we have a few new strings

**Comment by Dimillian** [comment]
In the plural dict

**Comment by arthurgivigir** [comment]
Shure! I'll do it now.

**Comment by arthurgivigir** [comment]
Hey @Dimillian! It's done! 😄

**Comment by Dimillian** [comment]
Thanks! Will look and merge tomorrow.

**Comment by arthurgivigir** [comment]
I made one last commit fixing a text on empty notification view 😉.

**Pull request merged**
