### PR TITLE
Change "publicació" or "publicacions" to "tut" and "tuts"

### PR DESCRIPTION
**Pull request by splaGit**
I would like to change these two catalan words "Publicació" and "Publicacions" to "Tut" and "Tuts".
We are mastodont.cat, the largest Catalan instance of the fediverse, did a poll to vote how we want spell "post" in catalan language. The winner was "tut".

[Here the poll](https://mastodont.cat/@spla/109309273532385959)

Captura de pantalla 2023-01-28 a les 19 45 59

### CODE REVIEW

**Comment by Dimillian** [comment]
What @rbnval think?

**Comment by splaGit** [comment]
@rbnval so besides errors (that can be fixed) seems that what largest Catalan instance of the fediverse voted and accepted as translation for "Publicació" is not important here?
cc @Dimillian

**Comment by Dimillian** [comment]
Then I don't understand why it's a 200 lines of diff for 1 word.

**Comment by Dimillian** [comment]
And for now the app use Post in English too so it's consistent as of right now.

**Comment by Dimillian** [comment]
And I don't speak Catalan so I need you guys to sort this out :)

**Comment by splaGit** [comment]
So seems that what the largest Catalan comunity of the fediverse voted is not important. I can tell them about this.

**Comment by splaGit** [comment]
I'm the admin of mastodont.cat, more than 7.000 registered users. I don't know who is @rbnval

**Comment by Dimillian** [comment]
He still did the initial localization before your guys. And your PR came just after I've merged. So I don't know what to do at this point.

**Comment by Dimillian** [comment]
Maybe brings other instance users in the mix the vet the translations?

**Comment by splaGit** [comment]
Well, that poll was voted by many catalan people of many fediverse instances. My server is one of the oldest of the whole fediverse ( April 2017) and it federates actually with over 12,000 remote instances.
I understant you @Dimillian, right, @rbnval was the first Catalan translation you received because I was trying to remember how pull request works, so many time since my last pull request heh).
Don't worry much about this, happen to me some times with the Mastodon translation (actually it has "tut")

**Comment by Dimillian** [comment]
Where are we with mistakes fixes on this one?

**Comment by splaGit** [comment]
> Where are we with mistakes fixes on this one?

If you need to release a new version including already merged catalan language please do it.

**Pull request closed without merging**
